---
# tasks file for roles/packages

- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure aptitude is installed
  apt:
    name: aptitude
    state: latest

- name: Ensure packages are installed
  apt:
    pkg:
    - vim
    - git
    - linux-headers-amd64
    - wireguard
    - build-essential
    - netcat-openbsd
    - tcpdump
    - nmap
    - whois
    state: latest

- name: Ensure hostnames are in /etc/hosts 
  blockinfile:
    path: /etc/hosts
    block: |
      78.47.62.125    lqb-gw1-fff gw-fff-nbg1-1
      159.69.22.55    lqb-gw2-fff gw-fff-nbg1-2
      88.99.188.147   ex1-bgw
      116.202.105.144 ex2-bgw
      157.90.25.145   ex3-gw
