---
# tasks file for babel

- name: Ensure packages are installed
  apt:
    pkg:
    - git
    - linux-headers-amd64
    - build-essential
    - netcat-openbsd
    - tcpdump
    - nmap
    - whois
    state: latest

- name: Ensure babeld is installed
  shell: |
    git clone https://github.com/jech/babeld || true
    cd babeld 
    git checkout babeld-1.9.2 
    make clean
    make
    make install
  args:
    chdir: /usr/local/src/
    creates: /usr/local/bin/babeld
  notify: "restart babeld"

- name: Ensure babeld systemd service is installed
  copy:
    src: babeld.service
    dest: /etc/systemd/system/babeld.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: "restart babeld"

- name: Ensure babeld default is installed
  copy:
    src: babeld.default
    dest: /etc/default/babeld
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: "restart babeld"

- name: Ensure babeld config is installed
  template:
    src: babeld.conf.j2
    dest: /etc/babeld.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: "restart babeld"

# Network
- name: Ensure IPv4 forwarding is enabled
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/10-babel.conf

- name: Ensure IPv6 forwarding is enabled
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_set: yes
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/10-babel.conf

- name: Ensure icmp_errors_use_inbound_ifaddr is enabled
  sysctl:
    name: net.ipv4.icmp_errors_use_inbound_ifaddr
    value: "1"
    sysctl_set: yes
    reload: yes
    state: present
    sysctl_file: /etc/sysctl.d/10-babel.conf

- name: Ensure babel routing table is enabled
  lineinfile:
    path: /etc/iproute2/rt_tables
    regexp: '^10\s*{{ babel_rt_name }}'
    line: '10     {{ babel_rt_name }}'
    state: present

- name: Ensure defaults are set for loopback
  blockinfile:
    path: /etc/network/interfaces
    block: |
      iface lo inet loopback
              post-up ip ru add from all to 10.0.0.0/8 lookup {{ babel_rt_name }}
              post-up ip ru add from 10.0.0.0/8 lookup {{ babel_rt_name }}

      {% if babel.exit_node | default(False) %}
      iface {{ ansible_default_ipv4.interface }} inet manual
              # babel exit node
              post-up ip route replace default via {{ ansible_default_ipv4.gateway }} dev {{ ansible_default_ipv4.interface }} proto static tab {{ babel_rt_name }}
              post-up iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.interface }} -j MASQUERADE
      {% endif %}
    marker: "### {mark} ANSIBLE MANAGED BLOCK (babel) ###"
  notify: "restart loopback"

- name: Ensure babeld is started
  systemd:
    name: babeld.service
    state: started
