---
babel_rt_name: fff

babel:
  ip4:
    address: "10.83.252.116/32"
  ip6:
    address: "fe80::4c51:4236:1/128"
  peers:
  - interface: wg_lqb_gw1_fff
    type: tunnel
    rxcost: 96
  redistribute:
  - 10.50.0.0/16
  - 10.83.0.0/16
  - fd43:5602:29bd::/48

wireguard:
  - interface: wg_lqb_gw1_fff
    template: wg-babel-peer.j2
    private_key: "{{ vault_wireguard.wg_lqb_gw1_fff.private_key }}"
    public_key: 3LQBhIPjqHQk+IL0z9IbReawazzHrSaXWlwdRKz7iTs=
    listen_port: 51822
    ip4:
      address: "{{ babel.ip4.address }}"
    ip6:
      address: "{{ babel.ip6.address }}"
    peers:
    - public_key: 4LQblVAyGT5lPs0ej1FX3U0Bd719dyl4+whcx7qPNww=
      allowed_ips: "0.0.0.0/0, ::0/0"
      endpoint: "lqb-gw1-fff:51822"
      persistent_keepalive: "25"

  - interface: wg1
    template: wg-babel-announce.j2
    private_key: "{{ vault_wireguard.wg1.private_key }}"
    public_key: 5lqbyd4c4t5kibc6rhxg3TitmSS/JMOqC+nLfppevn0=
    listen_port: 51821
    ip4:
      address: "10.83.229.1/24"
      network: "10.83.229.0/24"
    ip6:
      address: "fe80::4c51:4234:1/64"
      network: "fe80::4c51:4234:0/64"
    peers:
    - public_key: 6lQbdTbOzqi3RkjQmEZgHlPOaAuJPHHTkroonIA1GQE=
      allowed_ips: "10.83.229.0/24"
