---
gw_fff_peer_ip4_address: "10.83.252.116/32"
gw_fff_peer_ip6_address: "fe80::4c51:4236:1/128"

gw_fff_wireguard:
  wg_nbg11:
    secret_key: "{{ vault_gw_fff_wireguard.wg_nbg11.secret_key }}"
    public_key: 3LQBhIPjqHQk+IL0z9IbReawazzHrSaXWlwdRKz7iTs=
    listen_port: 51822
    ip4_address: "{{ gw_fff_peer_ip4_address }}"
    ip6_address: "{{ gw_fff_peer_ip6_address }}"
    peers:
    - public_key: 4LQblVAyGT5lPs0ej1FX3U0Bd719dyl4+whcx7qPNww=
      endpoint: 78.47.62.125:51822
      allowed_ips: "0.0.0.0/0, ::0/0"
      persistent_keepalive: "25"
    interface_template: wg-babel-peer.j2
  wg1:
    secret_key: "{{ vault_gw_fff_wireguard.wg1.secret_key }}"
    public_key: 5lqbyd4c4t5kibc6rhxg3TitmSS/JMOqC+nLfppevn0=
    listen_port: 51821
    ip4_address: "10.83.229.1/24"
    ip4_network: "10.83.229.0/24"
    ip6_address: "fe80::4c51:4234:1/64"
    peers:
    - public_key: 6lQbdTbOzqi3RkjQmEZgHlPOaAuJPHHTkroonIA1GQE=
      allowed_ips: 10.83.229.0/24
    interface_template: wg-babel-announce.j2



gw_fff_babel:
  - interface: wg_nbg11
    type: tunnel
    rxcost: 4096
